<?php
if(empty($template_data['type'])) {
	$template_data['type'] = "";
}

$template_type_array = array(
		"admin_reply_from_order"=>"Admin Reply from Order",
		"admin_reply_from_offer"=>"Admin Reply from Offer",
		"customer_reply_from_offer"=>"Customer Reply from Offer",
		"reset_password"=>"Send Password Reset Link To Customer",
		"new_order_email_to_customer"=>"New Order Email To Customer",
		"new_order_email_to_admin"=>"New Order Email To Admin",
		"signup_verification_for_email"=>"Signup Verification For Email",
		"customer_profile_edit_from_admin"=>"Customer Profile Edit From Admin",
		"contact_form_alert"=>"Contact Form Alert By Customer",
		"review_form_alert"=>"Review Form Alert To Admin",
		"review_thank_you_email_to_customer"=>"Review Thank You Email To Customer",
		"bulk_order_form_alert"=>"Bulk Order Form Alert To Admin",
		"bulk_order_thank_you_email_to_customer"=>"Bulk Order Thank You Email To Customer",
		"quote_request_form_alert"=>"Quote Request Form Alert By Customer",
		"affiliate_form_alert"=>"Affiliate Form Alert By Customer",
		"order_expiring"=>"Order Expiring (Automated)",
		"order_expired"=>"Order Expired (Automated)",
		"shipment_label_email_to_customer"=>"Shipment Label Email To Customer",
		"newsletter_thank_you_email_to_customer"=>"Newsletter Thank You Email To Customer",
		"newsletter_form_alert"=>"Newsletter Form Alert To Admin",
		"reset_password_app"=>"Send Password Reset Token To Customer (MobileApp)",
		"newsletter_email_to_bulk_customer"=>"Newsletter email to customer(s) by admin action",
		"order_item_status_waiting_shipment_from_admin"=>"Order Item Status Waiting Shipment From Admin",
		"order_item_status_absent_from_admin"=>"Order Item Status Absent From Admin",
		"order_item_status_checked_from_admin"=>"Order Item Status Checked From Admin",
		"order_item_status_price_is_reduced_from_admin"=>"Order Item Status Price Is Reduced From Admin",
		"order_item_status_price_is_accepted_from_admin"=>"Order Item Status Price Is Accepted From Admin",
		"order_item_status_price_is_declined_from_admin"=>"Order Item Status Price Is Declined From Admin",
		"order_item_status_returned_from_admin"=>"Order Item Status Returned From Admin",
		"order_item_status_paid_from_admin"=>"Order Item Status Paid From Admin",
		);

$to_admin_tmpl_array = array("customer_reply_from_offer","new_order_email_to_admin","contact_form_alert","review_form_alert","bulk_order_form_alert","quote_request_form_alert","affiliate_form_alert","newsletter_form_alert");

$to_customer_tmpl_array = array("admin_reply_from_order","admin_reply_from_offer","reset_password","signup_verification_for_email","customer_profile_edit_from_admin","review_thank_you_email_to_customer","bulk_order_thank_you_email_to_customer","order_expiring","order_expired","shipment_label_email_to_customer","newsletter_thank_you_email_to_customer","newsletter_email_to_bulk_customer","order_item_status_waiting_shipment_from_admin","order_item_status_absent_from_admin","order_item_status_checked_from_admin","order_item_status_price_is_reduced_from_admin","order_item_status_price_is_accepted_from_admin","order_item_status_price_is_declined_from_admin","order_item_status_returned_from_admin","order_item_status_paid_from_admin");

if($template_data['type']=="contact_form_alert") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$order_id}',
		'{$form_subject}',
		'{$form_message}',
		'{$current_date_time}');
} elseif($template_data['type']=="review_form_alert" || $template_data['type']=="review_thank_you_email_to_customer") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fullname}',
		'{$customer_email}',
		'{$country}',
		'{$state}',
		'{$city}',
		'{$stars}',
		'{$form_title}',
		'{$form_message}',
		'{$current_date_time}',
		'{$device_sold}');
} elseif($template_data['type']=="bulk_order_form_alert" || $template_data['type']=="bulk_order_thank_you_email_to_customer") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fullname}',
		'{$customer_email}',
		'{$country}',
		'{$state}',
		'{$city}',
		'{$zip_code}',
		'{$company_name}',
		'{$devices}',
		'{$form_message}',
		'{$current_date_time}');
} elseif($template_data['type']=="affiliate_form_alert") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$current_date_time}',
		'{$company_name}',
		'{$web_address}',
		'{$form_subject}',
		'{$form_message}',
		'{$item_name}');
} elseif($template_data['type']=="quote_request_form_alert") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$current_date_time}',
		'{$form_subject}',
		'{$form_message}',
		'{$item_name}');
} elseif($template_data['type']=="signup_verification_for_email") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fname}',
		'{$customer_lname}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$billing_address1}',
		'{$billing_address2}',
		'{$billing_city}',
		'{$billing_state}',
		'{$customer_country}',
		'{$billing_postcode}',
		'{$current_date_time}',
		'{$verification_code}',
		'{$verification_link}',
		'{$admin_phone}');
} elseif($template_data['type']=="new_order_email_to_admin" || $template_data['type']=="new_order_email_to_customer") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fname}',
		'{$customer_lname}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$billing_address1}',
		'{$billing_address2}',
		'{$billing_city}',
		'{$billing_state}',
		'{$customer_country}',
		'{$billing_postcode}',
		'{$order_id}',
		'{$order_payment_method}',
		'{$order_date}',
		'{$order_approved_date}',
		'{$order_expire_date}',
		'{$order_status}',
		'{$order_sales_pack}',
		'{$current_date_time}',
		'{$order_item_list}',
		'{$order_instruction}',
		'{$company_name}',
		'{$company_address}',
		'{$company_city}',
		'{$company_state}',
		'{$company_postcode}',
		'{$company_country}',
		'{$shipping_fname}',
		'{$shipping_lname}',
		'{$shipping_company_name}',
		'{$shipping_address1}',
		'{$shipping_address2}',
		'{$shipping_city}',
		'{$shipping_state}',
		'{$shipping_postcode}',
		'{$shipping_phone}');
} elseif($template_data['type']=="customer_profile_edit_from_admin") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fname}',
		'{$customer_lname}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$customer_password}',
		'{$billing_address1}',
		'{$billing_address2}',
		'{$billing_city}',
		'{$billing_state}',
		'{$customer_country}',
		'{$billing_postcode}',
		'{$customer_status}',
		'{$current_date_time}');
} elseif($template_data['type']=="reset_password") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_url}',
		'{$customer_fname}',
		'{$customer_lname}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$billing_address1}',
		'{$billing_address2}',
		'{$billing_city}',
		'{$billing_state}',
		'{$customer_country}',
		'{$billing_postcode}',
		'{$current_date_time}',
		'{$password_reset_link}');
} elseif($template_data['type']=="admin_reply_from_order") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fname}',
		'{$customer_lname}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$billing_address1}',
		'{$billing_address2}',
		'{$billing_city}',
		'{$billing_state}',
		'{$customer_country}',
		'{$billing_postcode}',
		'{$customer_company_name}',
		'{$order_id}',
		'{$order_payment_method}',
		'{$order_date}',
		'{$order_approved_date}',
		'{$order_expire_date}',
		'{$order_status}',
		'{$order_sales_pack}',
		'{$current_date_time}',
		'{$shipping_fname}',
		'{$shipping_lname}',
		'{$shipping_company_name}',
		'{$shipping_address1}',
		'{$shipping_address2}',
		'{$shipping_city}',
		'{$shipping_state}',
		'{$shipping_postcode}',
		'{$shipping_phone}');
} elseif($template_data['type']=="order_item_status_waiting_shipment_from_admin"
		|| $template_data['type']=="order_item_status_absent_from_admin"
		|| $template_data['type']=="order_item_status_checked_from_admin"
		|| $template_data['type']=="order_item_status_price_is_reduced_from_admin"
		|| $template_data['type']=="order_item_status_price_is_accepted_from_admin"
		|| $template_data['type']=="order_item_status_price_is_declined_from_admin"
		|| $template_data['type']=="order_item_status_returned_from_admin"
		|| $template_data['type']=="order_item_status_paid_from_admin") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fname}',
		'{$customer_lname}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$billing_address1}',
		'{$billing_address2}',
		'{$billing_city}',
		'{$billing_state}',
		'{$customer_country}',
		'{$billing_postcode}',
		'{$customer_company_name}',
		'{$order_id}',
		'{$order_payment_method}',
		'{$order_date}',
		'{$order_approved_date}',
		'{$order_expire_date}',
		'{$order_status}',
		'{$order_sales_pack}',
		'{$current_date_time}',
		'{$shipping_fname}',
		'{$shipping_lname}',
		'{$shipping_company_name}',
		'{$shipping_address1}',
		'{$shipping_address2}',
		'{$shipping_city}',
		'{$shipping_state}',
		'{$shipping_postcode}',
		'{$shipping_phone}',
		'{$order_item_id}',
		'{$order_item_status}',
		'{$order_item_name}',
		'{$order_item_prev_price}',
		'{$order_item_current_price}',
		'{$offer_accept_link}',
		'{$offer_reject_link}');
} elseif($template_data['type']=="admin_reply_from_offer") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fname}',
		'{$customer_lname}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$billing_address1}',
		'{$billing_address2}',
		'{$billing_city}',
		'{$billing_state}',
		'{$customer_country}',
		'{$billing_postcode}',
		'{$customer_company_name}',
		'{$order_id}',
		'{$order_payment_method}',
		'{$order_date}',
		'{$order_approved_date}',
		'{$order_expire_date}',
		'{$order_status}',
		'{$order_sales_pack}',
		'{$current_date_time}',
		'{$order_note}',
		'{$order_item_list}',
		'{$offer_accept_link}',
		'{$offer_reject_link}',
		'{$company_name}',
		'{$company_address}',
		'{$company_city}',
		'{$company_state}',
		'{$company_postcode}',
		'{$company_country}',
		'{$shipping_fname}',
		'{$shipping_lname}',
		'{$shipping_company_name}',
		'{$shipping_address1}',
		'{$shipping_address2}',
		'{$shipping_city}',
		'{$shipping_state}',
		'{$shipping_postcode}',
		'{$shipping_phone}');
} elseif($template_data['type']=="customer_reply_from_offer") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fname}',
		'{$customer_lname}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$billing_address1}',
		'{$billing_address2}',
		'{$billing_city}',
		'{$billing_state}',
		'{$customer_country}',
		'{$billing_postcode}',
		'{$order_id}',
		'{$order_payment_method}',
		'{$order_date}',
		'{$order_approved_date}',
		'{$order_expire_date}',
		'{$order_status}',
		'{$offer_status}',
		'{$order_sales_pack}',
		'{$current_date_time}',
		'{$order_note}',
		'{$order_item_list}',
		'{$company_name}',
		'{$company_address}',
		'{$company_city}',
		'{$company_state}',
		'{$company_postcode}',
		'{$company_country}',
		'{$shipping_fname}',
		'{$shipping_lname}',
		'{$shipping_company_name}',
		'{$shipping_address1}',
		'{$shipping_address2}',
		'{$shipping_city}',
		'{$shipping_state}',
		'{$shipping_postcode}',
		'{$shipping_phone}');
} elseif($template_data['type']=="shipment_label_email_to_customer") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fullname}',
		'{$customer_email}',
		'{$country}',
		'{$state}',
		'{$city}',
		'{$order_id}',
		'{$order_payment_method}',
		'{$order_date}',
		'{$order_approved_date}',
		'{$order_expire_date}',
		'{$order_status}',
		'{$order_sales_pack}',
		'{$current_date_time}');
} elseif($template_data['type']=="reset_password_app") {
	$constants_array = array(
		'{$customer_fullname}',
		'{$password_reset_token}',
		'{$logo}',
		'{$company_name}',
		'{$site_url}');
} elseif($template_data['type']=="newsletter_form_alert" || $template_data['type']=="newsletter_thank_you_email_to_customer") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fullname}',
		'{$customer_fname}',
		'{$customer_lname}',
		'{$customer_phone}',
		'{$customer_email}');
} elseif($template_data['type']=="order_expiring" || $template_data['type']=="order_expired") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_phone}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fname}',
		'{$customer_lname}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$billing_address1}',
		'{$billing_address2}',
		'{$billing_city}',
		'{$billing_state}',
		'{$customer_country}',
		'{$billing_postcode}',
		'{$order_id}',
		'{$order_payment_method}',
		'{$order_date}',
		'{$order_approved_date}',
		'{$order_expire_date}',
		'{$order_status}',
		'{$order_sales_pack}',
		'{$current_date_time}',
		'{$order_item_list}',
		'{$company_name}',
		'{$company_address}',
		'{$company_city}',
		'{$company_state}',
		'{$company_postcode}',
		'{$company_country}',
		'{$unsubscribe_link}');
} elseif($template_data['type']=="newsletter_thank_you_email_to_customer") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$current_date_time}',
		'{$customer_email}');
} else {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fname}',
		'{$customer_lname}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$billing_address1}',
		'{$billing_address2}',
		'{$billing_city}',
		'{$billing_state}',
		'{$customer_country}',
		'{$billing_postcode}',
		'{$customer_company_name}',
		'{$order_id}',
		'{$order_payment_method}',
		'{$order_date}',
		'{$order_approved_date}',
		'{$order_expire_date}',
		'{$order_status}',
		'{$order_sales_pack}',
		'{$current_date_time}',
		'{$shipping_fname}',
		'{$shipping_lname}',
		'{$shipping_company_name}',
		'{$shipping_address1}',
		'{$shipping_address2}',
		'{$shipping_city}',
		'{$shipping_state}',
		'{$shipping_postcode}',
		'{$shipping_phone}',
		'{$dollars_spent_order}',
		'{$unsubscribe_link}');
}
?>
