<?php
$template_type_array = array(
		"admin_reply_from_order"=>"Admin Reply from Order",
		"admin_reply_from_offer"=>"Admin Reply from Offer",
		"customer_reply_from_offer"=>"Customer Reply from Offer",
		"reset_password"=>"Send Password Reset Link To Customer",
		"new_order_email_to_customer_own_print_label"=>"New Order Email To Customer (Own Print Label)",
		"new_order_email_to_customer_send_me_label"=>"New Order Email To Customer (Send Me Label)",
		"new_order_email_to_customer_courier_collection"=>"New Order Email To Customer (Courier Collection)",
		"new_order_email_to_customer_own_method"=>"New Order Email To Customer (Own Method)",
		"new_order_email_to_admin"=>"New Order Email To Admin",
		"signup_verification_for_email"=>"Signup Verification For Email",
		"customer_profile_edit_from_admin"=>"Customer Profile Edit From Admin",
		"contact_form_alert"=>"Contact Form Alert By Customer",
		"review_form_alert"=>"Review Form Alert To Admin",
		"review_thank_you_email_to_customer"=>"Review Thank You Email To Customer",
		"bulk_order_form_alert"=>"Bulk Order Form Alert To Admin",
		"bulk_order_thank_you_email_to_customer"=>"Bulk Order Thank You Email To Customer",
		"quote_request_form_alert"=>"Quote Request Form Alert By Customer",
		"affiliate_form_alert"=>"Affiliate Form Alert By Customer",
		"order_expiring"=>"Order Expiring (Automated)",
		"order_expired"=>"Order Expired (Automated)",
		"shipment_label_email_to_customer"=>"Shipment Label Email To Customer",
		);

$to_admin_tmpl_array = array("customer_reply_from_offer","new_order_email_to_admin","contact_form_alert","quote_request_form_alert","affiliate_form_alert");
$to_customer_tmpl_array = array("admin_reply_from_order","admin_reply_from_offer","reset_password","new_order_email_to_customer","signup_verification_for_email","customer_profile_edit_from_admin","order_expiring","order_expired");

if($template_data['type']=="contact_form_alert") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$order_id}',
		'{$form_subject}',
		'{$form_message}');
} elseif($template_data['type']=="review_form_alert") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fullname}',
		'{$customer_email}',
		'{$country}',
		'{$state}',
		'{$city}',
		'{$stars}',
		'{$form_title}',
		'{$form_message}');
} elseif($template_data['type']=="review_thank_you_email_to_customer") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fullname}',
		'{$customer_email}',
		'{$country}',
		'{$state}',
		'{$city}',
		'{$stars}',
		'{$form_title}',
		'{$form_message}');
} elseif($template_data['type']=="bulk_order_form_alert") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fullname}',
		'{$customer_email}',
		'{$country}',
		'{$state}',
		'{$city}',
		'{$zip_code}',
		'{$company_name}',
		'{$devices}',
		'{$form_message}');
} elseif($template_data['type']=="bulk_order_thank_you_email_to_customer") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fullname}',
		'{$customer_email}',
		'{$country}',
		'{$state}',
		'{$city}',
		'{$zip_code}',
		'{$company_name}',
		'{$devices}',
		'{$form_message}');
} elseif($template_data['type']=="affiliate_form_alert") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$current_date_time}',
		'{$company_name}',
		'{$web_address}',
		'{$form_subject}',
		'{$form_message}',
		'{$item_name}');
} elseif($template_data['type']=="quote_request_form_alert") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$current_date_time}',
		'{$form_subject}',
		'{$form_message}',
		'{$item_name}');
} elseif($template_data['type']=="signup_verification_for_email") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fname}',
		'{$customer_lname}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$customer_address_line1}',
		'{$customer_address_line2}',
		'{$customer_city}',
		'{$customer_state}',
		'{$customer_country}',
		'{$customer_postcode}',
		'{$current_date_time}',
		'{$verification_code}',
		'{$verification_link}',
		'{$admin_phone}');
} elseif($template_data['type']=="new_order_email_to_customer_own_print_label" || $template_data['type']=="new_order_email_to_customer_send_me_label" || $template_data['type']=="new_order_email_to_customer_courier_collection" || $template_data['type']=="new_order_email_to_customer_own_method" || $template_data['type']=="new_order_email_to_admin") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fname}',
		'{$customer_lname}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$customer_address_line1}',
		'{$customer_address_line2}',
		'{$customer_city}',
		'{$customer_state}',
		'{$customer_country}',
		'{$customer_postcode}',
		'{$order_id}',
		'{$order_payment_method}',
		'{$order_date}',
		'{$order_approved_date}',
		'{$order_expire_date}',
		'{$order_status}',
		'{$order_sales_pack}',
		'{$current_date_time}',
		'{$order_item_list}',
		'{$company_name}',
		'{$company_address}',
		'{$company_city}',
		'{$company_state}',
		'{$company_postcode}',
		'{$company_country}');
} elseif($template_data['type']=="customer_profile_edit_from_admin") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fname}',
		'{$customer_lname}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$customer_password}',
		'{$customer_address_line1}',
		'{$customer_address_line2}',
		'{$customer_city}',
		'{$customer_state}',
		'{$customer_country}',
		'{$customer_postcode}',
		'{$customer_status}',
		'{$current_date_time}');
} elseif($template_data['type']=="reset_password") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_url}',
		'{$customer_fname}',
		'{$customer_lname}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$customer_address_line1}',
		'{$customer_address_line2}',
		'{$customer_city}',
		'{$customer_state}',
		'{$customer_country}',
		'{$customer_postcode}',
		'{$current_date_time}',
		'{$password_reset_link}');
} elseif($template_data['type']=="admin_reply_from_order") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_url}',
		'{$customer_fname}',
		'{$customer_lname}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$customer_address_line1}',
		'{$customer_address_line2}',
		'{$customer_city}',
		'{$customer_state}',
		'{$customer_country}',
		'{$customer_postcode}',
		'{$customer_company_name}',
		'{$order_id}',
		'{$order_payment_method}',
		'{$order_date}',
		'{$order_approved_date}',
		'{$order_expire_date}',
		'{$order_sales_pack}',
		'{$current_date_time}',
		'{$company_name}',
		'{$company_address}',
		'{$company_city}',
		'{$company_state}',
		'{$company_postcode}',
		'{$company_country}');
} elseif($template_data['type']=="admin_reply_from_offer") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fname}',
		'{$customer_lname}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$customer_address_line1}',
		'{$customer_address_line2}',
		'{$customer_city}',
		'{$customer_state}',
		'{$customer_country}',
		'{$customer_postcode}',
		'{$customer_company_name}',
		'{$order_id}',
		'{$order_payment_method}',
		'{$order_date}',
		'{$order_approved_date}',
		'{$order_expire_date}',
		'{$order_status}',
		'{$order_sales_pack}',
		'{$current_date_time}',
		'{$order_note}',
		'{$order_item_list}',
		'{$offer_accept_link}',
		'{$offer_reject_link}',
		'{$company_name}',
		'{$company_address}',
		'{$company_city}',
		'{$company_state}',
		'{$company_postcode}',
		'{$company_country}');
} elseif($template_data['type']=="customer_reply_from_offer") {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fname}',
		'{$customer_lname}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$customer_address_line1}',
		'{$customer_address_line2}',
		'{$customer_city}',
		'{$customer_state}',
		'{$customer_country}',
		'{$customer_postcode}',
		'{$order_id}',
		'{$order_payment_method}',
		'{$order_date}',
		'{$order_approved_date}',
		'{$order_expire_date}',
		'{$order_status}',
		'{$offer_status}',
		'{$order_sales_pack}',
		'{$current_date_time}',
		'{$order_note}',
		'{$order_item_list}',
		'{$company_name}',
		'{$company_address}',
		'{$company_city}',
		'{$company_state}',
		'{$company_postcode}',
		'{$company_country}');
} else {
	$constants_array = array(
		'{$logo}',
		'{$admin_logo}',
		'{$admin_email}',
		'{$admin_username}',
		'{$admin_site_url}',
		'{$admin_panel_name}',
		'{$admin_phone}',
		'{$from_name}',
		'{$from_email}',
		'{$site_name}',
		'{$site_url}',
		'{$customer_fname}',
		'{$customer_lname}',
		'{$customer_fullname}',
		'{$customer_phone}',
		'{$customer_email}',
		'{$customer_password}',
		'{$customer_address_line1}',
		'{$customer_address_line2}',
		'{$customer_city}',
		'{$customer_state}',
		'{$customer_country}',
		'{$customer_postcode}',
		'{$customer_status}',
		'{$order_id}',
		'{$order_payment_method}',
		'{$order_date}',
		'{$order_approved_date}',
		'{$order_expire_date}',
		'{$order_status}',
		'{$offer_status}',
		'{$verification_link}',
		'{$verification_code}',
		'{$password_reset_link}',
		'{$order_note}',
		'{$order_item_list}',
		'{$offer_accept_link}',
		'{$offer_reject_link}',
		'{$web_address}',
		'{$company_name}',
		'{$company_address}',
		'{$company_city}',
		'{$company_state}',
		'{$company_postcode}',
		'{$company_country}');
}
?>